version: '2'
services:
  py27:
    # Build using the Dockerfile in this directory
    build: .
    volumes:
      # Mount for ....
      - ./udf:/code
      #mount for unix socket communication
      - /volume1/docker/sandbox/kapacitor:/kapacitor
      - /volume1/docker/sandbox/kapacitor/data/tmp:/tmp
    #links:
      # Chronograf requires network access to InfluxDB and Kapacitor
    #  - influxdb
    #  - kapacitor

    # No requirement for network access at present UDF comms over unix-socket
    # If the UDF requires telemetry this may change

    #ports:
      # The ........................ on port .....
      #- "5000:5000"
